### ISSUE TITLE
Issue when attempting to encode

### ISSUE THREAD

**Issue by ThracianKnight1907** [Vargol/spatial-media#8]
Hello,

As the title says I get the following error when trying to encode (sorry i can't paste it):
![Screenshot from 2022-10-20 09-34-32](https://user-images.githubusercontent.com/64692701/196875716-1fdbb4a1-7f76-4c1e-9613-320b64dd238d.png)
I'm not sure what I'm doing wrong. I am using Fedora 36 with mostly default settings and never messed with the python packages.

**Comment by Vargol** [comment]
I'd guess by the trace your filename has a character in it that it can't convert for printing out, “ă” .

**Comment by ThracianKnight1907** [comment]
Yes, that was the issue. Thank you!
